# Generated by Django 3.0.7 on 2021-04-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emoji',
            table='emoji',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
