# Generated by Django 3.0.7 on 2021-04-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20210423_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='tags',
            field=models.TextField(max_length=500),
        ),
    ]
