# Generated by Django 3.0.7 on 2021-05-09 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20210509_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emoji',
            name='uuid',
        ),
    ]
